language: generic
install:
    - git clone https://github.com/thinca/vim-themis && (cd vim-themis && git show HEAD)
before_script:
    - uname -a
    - vim --version
    - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /var/lib/locales/supported.d/local
    - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen
    - sudo /usr/sbin/locale-gen
script:
    - ./vim-themis/bin/themis test/
